---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Home
  create: all
  match: "**/*"
  templates:
  - about-page
- type: directory
  path: beers
  label: Beers
  create: all
  match: "**/*"
  templates:
  - blog
- type: heading
  label: Brewery Catering
- type: directory
  path: catering/history
  label: First Brewery Incarnation
  create: all
  match: "**/*"
  templates:
  - blog
- type: directory
  path: catering/must-own
  label: 5 Things Every Beer Lover Must Own
  create: all
  match: "**/*"
  templates:
  - blog
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
